

/**
 * Common constants for all features.
 */
class CommonConstants {
  /**
   * Duration of prompt.
   */
  DURATION: number = 3000;

  /**
   * The fruit name tag.
   */
  FRUIT_FLAG: number = 0;

  /**
   * The fruit number tag.
   */
  NUMBER_FLAG: number = 1;

  /**
   * The tag is used to print log.
   */
  TAG = '[PreferenceModel]';

  /**
   * The key value of the data store.
   */
  KEY_NAME = 'fruit';

  /**
   * The name of the data store.
   */
  PREFERENCES_NAME = 'fruit.db';
}

export default new CommonConstants();