class StyleConstants {
  /**
   * Font size.
   */
  FONT_SIZE = 20;

  /**
   * Font weight.
   */
  FONT_WEIGHT = 500;

  /**
   * One hundred percent.
   */
  FULL_PERCENT = '100%';

  /**
   * The font size of text component.
   */
  TEXT_FONT_SIZE = 25;

  /**
   * The height of text component.
   */
  TEXT_HEIGHT = '24vp';

  /**
   * The height of textInput component.
   */
  TEXT_INPUT_HEIGHT = '7%';

  /**
   * The width of textInput component.
   */
  TEXT_INPUT_WIDTH = '93%';

  /**
   * The bottom margin of the text component.
   */
  TEXT_MARGIN_BOTTOM = '3%';

  /**
   * The left margin of the text component.
   */
  TEXT_MARGIN_LEFT = '10%';

  /**
   * Letter spacing.
   */
  LETTER_SPACING = '1.58';

  /**
   * Margin top
   */
  MARGIN_TOP = '12%';

  /**
   * Small margin bottom
   */
  MARGIN_BOTTOM_SMALL = '6%';

  /**
   * Big margin bottom
   */
  MARGIN_BOTTOM_BIG = '250vp';

  /**
   * The height of button component.
   */
  BUTTON_HEIGHT = '6%';

  /**
   * The width of button component.
   */
  BUTTON_WIDTH = '87%';

  /**
   * The bottom margin of the button component.
   */
  BUTTON_MARGIN_BOTTOM = '24vp';
}

export default new StyleConstants();